<?php

namespace App\Console\Commands;

use App\Models\HR\Attendance;
use App\Models\HR\Employee;
use App\Models\HR\LeaveRequest;
use Illuminate\Console\Command;
use Illuminate\Support\Carbon;

class GenerateDailyAbsence extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'attendance:generate-absent';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate data untuk karyawan yang tidak presensi dan tidak cuti hari ini';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $today = Carbon::today();
        
        // 1. Cek apakah hari ini hari libur (Weekend) ?
        // Jika kantor libur sabtu-minggu, skip proses ini.
        if ($today->isWeekend()) {
            $this->info('Hari ini weekend, tidak ada generate tidak presensi.');
            return;
        }

        // 2. Ambil semua karyawan yang statusnya aktif
        // Asumsi ada kolom 'status' = 'active' di tabel employees
        $employees = Employee::where('status', 'active')->get();

        $count = 0;

        foreach ($employees as $employee) {
            
            // A. Cek apakah karyawan sudah absen hari ini (hadir/terlambat)
            $hasAttendance = Attendance::query()
                ->where('employee_id', $employee->id)
                ->whereDate('date', $today)
                ->exists();

            if ($hasAttendance) {
                continue; // Skip, karena dia hadir
            }

            // B. Cek apakah karyawan sedang cuti (Approved)
            $onLeave = LeaveRequest::query()
                ->where('employee_id', $employee->id)
                ->where('status', 'approved')
                ->where(function ($q) use ($today) {
                    $q->whereDate('start_date', '<=', $today)
                      ->whereDate('end_date', '>=', $today);
                })
                ->exists();

            if ($onLeave) {
                
                // Opsional: Jika ingin mencatat data 'Cuti' ke tabel attendance 
                // agar laporan harian lengkap, bisa insert di sini dengan status 'leave'.
                // Jika tidak, cukup continue.
                continue; 
            }

            // C. Jika tidak hadir & tidak cuti, maka buat data tidak presensi
            Attendance::create([
                'employee_id' => $employee->id,
                'shift_id'    => $employee->shift_id, // Ambil shift default karyawan
                'date'        => $today,
                'status'      => 'absen',
                'note'        => 'Generated by System (Tidak Presensi/Tanpa Keterangan)',
                'clock_in'    => null,
                'clock_out'   => null,
            ]);

            $count++;
        }

        $this->info("Berhasil generate {$count} data tidak presensi untuk tanggal {$today->format('Y-m-d')}.");
    }
}
