name: Deploy via SFTP
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout source code
      - uses: actions/checkout@v4

      # 2️⃣ Setup PHP dan Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      # 3️⃣ Install dependensi Laravel
      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      # 4️⃣ Install dependensi npm & build filament
      - name: Build Filament assets
        run: npm install && npm run build:filament

      # 5️⃣ Deploy via SFTP
      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          local_path: './public'
          remote_path: '/home/arihu975/public_html/domains/erp.arihub.my.id'
          sftp_only: true
